/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/watch/lineups': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listWatchLineups'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/watch/lineups/{lineup_id}/channels': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listWatchChannels'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/watch/lineups/{lineup_id}/guide': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['getWatchGuide'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/watch/channels/{channel_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['getWatchChannel'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['searchXivi'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/overview': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['getStudioOverview'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/guide-data/coverage': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['getGuideCoverage'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/lineups': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listStudioLineups'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/lineups/{lineup_id}/groups': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listStudioLineupGroups'];
		put?: never;
		post: operations['createStudioGroup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/source-groups': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listSourceGroups'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/lineups/{lineup_id}/source-groups/{source_group_id}/copy': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['copySourceGroupToLineup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/lineups/{lineup_id}/groups/{group_id}/position': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch: operations['moveWorkspaceGroup'];
		trace?: never;
	};
	'/studio/groups/{group_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations['deleteStudioGroup'];
		options?: never;
		head?: never;
		patch: operations['updateStudioGroup'];
		trace?: never;
	};
	'/studio/groups/{group_id}/source-link': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations['setGroupSourceLink'];
		post?: never;
		delete: operations['disconnectGroupSourceLink'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/groups/{group_id}/sync': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['syncSourceGroup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/groups/{group_id}/channels': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listWorkspaceChannels'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/groups/{group_id}/channels/batch-add': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['batchAddWorkspaceChannels'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/groups/{group_id}/source-groups/{source_group_id}/add': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['addSourceGroupToStudioGroup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/groups/{group_id}/channels/batch-remove': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['batchRemoveWorkspaceChannels'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/groups/{group_id}/channels/batch-move': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['batchMoveWorkspaceChannels'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/groups/{group_id}/channels/{channel_id}/position': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch: operations['moveWorkspaceChannel'];
		trace?: never;
	};
	'/studio/channels/{channel_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch: operations['updateWorkspaceChannel'];
		trace?: never;
	};
	'/studio/source-channels': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listSourceChannels'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/source-channels/enabled': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch: operations['setSourceChannelsEnabled'];
		trace?: never;
	};
	'/studio/review': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listMatchReview'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/channels/{channel_id}/matches': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listChannelMatches'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/channels/{channel_id}/rejections': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listChannelMatchRejections'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/channels/{channel_id}/matches/{source_channel_id}/accept': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['acceptChannelMatch'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/channels/{channel_id}/matches/{source_channel_id}/reject': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['rejectChannelMatch'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/sources/{source_id}/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['refreshPlaylistSource'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/guide-data/sources/{source_id}/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['refreshGuideSource'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studio/lineups/{lineup_id}/publish': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['publishLineup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/jobs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['listJobs'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/jobs/{job_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['getJob'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['subscribeToEvents'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		APIError: {
			code: string;
			message: string;
			field_errors?: {
				[key: string]: string;
			};
			retryable: boolean;
		};
		PageMetadata: {
			next_cursor?: string | null;
			/** Format: int64 */
			total: number;
		};
		LineupSummary: {
			/** Format: int64 */
			id: number;
			name: string;
			/** Format: int64 */
			group_count: number;
			/** Format: int64 */
			channel_count: number;
			/** Format: double */
			epg_coverage: number;
		};
		Programme: {
			/** Format: int64 */
			id: number;
			channel_id: string;
			title: string;
			subtitle?: string;
			description?: string;
			categories: string[];
			/** Format: date-time */
			start: string;
			/** Format: date-time */
			end: string;
		};
		GuideChannel: {
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			number: number;
			name: string;
			tvg_id?: string;
			logo_url?: string;
			/** Format: int64 */
			group_id: number;
			group_name: string;
			stream_url: string;
			programmes: components['schemas']['Programme'][];
			current?: components['schemas']['Programme'];
			next?: components['schemas']['Programme'];
		};
		StudioGroup: {
			/** Format: int64 */
			id: number;
			name: string;
			/** Format: int64 */
			order: number;
			/** Format: int64 */
			channel_count: number;
			source_link?: components['schemas']['SourceGroupLink'];
		};
		StudioGroupCreateRequest: {
			name: string;
			source_link?: components['schemas']['SourceGroupLinkRequest'];
		};
		StudioGroupUpdateRequest: {
			name: string;
		};
		StudioGroupCreateResult: {
			/** Format: int64 */
			group_id: number;
			/** Format: int64 */
			job_id?: number;
			status?: string;
		};
		SourceGroup: {
			/** Format: int64 */
			id: number;
			name: string;
			/** Format: int64 */
			playlist_id: number;
			playlist_name: string;
			/** Format: int64 */
			channel_count: number;
			enabled: boolean;
			/** Format: int64 */
			linked_group_count: number;
		};
		SourceGroupLink: {
			/** Format: int64 */
			group_id: number;
			/** Format: int64 */
			playlist_id: number;
			playlist_name: string;
			/** Format: int64 */
			source_group_id?: number;
			source_group_name: string;
			follow_group_name: boolean;
			follow_channel_names: boolean;
			/** @enum {string} */
			status: 'pending' | 'active' | 'disconnected' | 'error';
			/** Format: date-time */
			last_synced_at?: string;
			last_error?: string;
			/** Format: int64 */
			added_count: number;
			/** Format: int64 */
			updated_count: number;
			/** Format: int64 */
			removed_count: number;
		};
		SourceGroupLinkRequest: {
			/** Format: int64 */
			source_group_id: number;
			follow_group_name: boolean;
			follow_channel_names: boolean;
		};
		SourceGroupImportResult: {
			/** Format: int64 */
			group_id: number;
			group_name: string;
			/** Format: int64 */
			added_count: number;
			/** Format: int64 */
			skipped_count: number;
		};
		PositionRequest: {
			/** Format: int64 */
			before_id?: number;
			/** Format: int64 */
			after_id?: number;
		} & (unknown | unknown);
		WorkspaceChannel: {
			/** Format: int64 */
			id: number;
			name: string;
			tvg_id?: string;
			uuid: string;
			/** Format: int64 */
			logo_id: number;
			logo_url?: string;
			/** Format: int64 */
			order: number;
			/** Format: int64 */
			source_count: number;
			match_method: string;
			/** Format: double */
			match_score?: number;
			/** Format: double */
			runner_up_score?: number;
			manual_locked: boolean;
		};
		WorkspaceChannelUpdate: {
			name: string;
			tvg_id?: string | null;
			/** Format: int64 */
			logo_id?: number | null;
		};
		WorkspaceBatchAddRequest: {
			source_channel_ids: number[];
		};
		WorkspaceBatchRemoveRequest: {
			channel_ids: number[];
		};
		WorkspaceBatchMoveRequest: {
			channel_ids: number[];
			/** Format: int64 */
			target_group_id: number;
			/** Format: int64 */
			before_id?: number;
			/** Format: int64 */
			after_id?: number;
		};
		SourceChannel: {
			/** Format: int64 */
			id: number;
			name: string;
			tvg_id?: string;
			logo_url?: string;
			enabled: boolean;
			/** Format: int64 */
			group_id: number;
			group_name: string;
			/** Format: int64 */
			playlist_id: number;
			playlist_name: string;
		};
		MatchReview: {
			/** Format: int64 */
			channel_id: number;
			channel_name: string;
			/** Format: int64 */
			source_channel_id: number;
			source_name: string;
			playlist_name: string;
			method: string;
			/** Format: double */
			score?: number;
			/** Format: double */
			runner_up_score?: number;
			manual_locked: boolean;
		};
		MatchRejection: {
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			channel_id: number;
			/** Format: int64 */
			playlist_id: number;
			playlist_name: string;
			tvg_id: string;
			name: string;
			/** Format: date-time */
			created_at: string;
		};
		StudioOverview: {
			/** Format: int64 */
			lineup_count: number;
			/** Format: int64 */
			source_count: number;
			/** Format: int64 */
			source_channel_count: number;
			/** Format: int64 */
			lineup_channel_count: number;
			/** Format: int64 */
			mapped_channel_count: number;
			/** Format: int64 */
			review_count: number;
			/** Format: int64 */
			low_confidence_count: number;
			/** Format: int64 */
			unmatched_count: number;
			/** Format: double */
			epg_coverage: number;
			/** Format: int64 */
			logo_count: number;
		};
		CoverageSummary: {
			/** Format: int64 */
			epg_channel_count: number;
			/** Format: int64 */
			programme_count: number;
			/** Format: int64 */
			mapped_channel_count: number;
			/** Format: int64 */
			lineup_channel_count: number;
			/** Format: double */
			coverage: number;
			unmapped_epg_ids: string[];
			channels_without_tvg_id: string[];
		};
		OperationJob: {
			/** Format: int64 */
			id: number;
			kind: string;
			resource: string;
			/** Format: int64 */
			resource_id?: number;
			/** @enum {string} */
			status: 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';
			progress: number;
			message?: string;
			error_code?: string;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
			/** Format: date-time */
			finished_at?: string;
		};
		OperationJobReference: {
			/** Format: int64 */
			job_id: number;
			status: string;
		};
		LineupPage: components['schemas']['PageMetadata'] & {
			items?: components['schemas']['LineupSummary'][];
		};
		GuideChannelPage: components['schemas']['PageMetadata'] & {
			items?: components['schemas']['GuideChannel'][];
		};
		StudioGroupPage: components['schemas']['PageMetadata'] & {
			items?: components['schemas']['StudioGroup'][];
		};
		WorkspaceChannelPage: components['schemas']['PageMetadata'] & {
			items?: components['schemas']['WorkspaceChannel'][];
		};
		SourceChannelPage: components['schemas']['PageMetadata'] & {
			items?: components['schemas']['SourceChannel'][];
		};
		SourceGroupPage: components['schemas']['PageMetadata'] & {
			items?: components['schemas']['SourceGroup'][];
		};
		MatchReviewPage: components['schemas']['PageMetadata'] & {
			items?: components['schemas']['MatchReview'][];
		};
		MatchRejectionPage: components['schemas']['PageMetadata'] & {
			items?: components['schemas']['MatchRejection'][];
		};
		OperationJobPage: components['schemas']['PageMetadata'] & {
			items?: components['schemas']['OperationJob'][];
		};
	};
	responses: {
		/** @description Standard Xivi error. */
		Error: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['APIError'];
			};
		};
		/** @description Paginated lineups. */
		LineupPage: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['LineupPage'];
			};
		};
		/** @description Paginated channels. */
		GuideChannelPage: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['GuideChannelPage'];
			};
		};
		/** @description Background operation accepted. */
		JobAccepted: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': {
					/** Format: int64 */
					job_id: number;
					/** @enum {string} */
					status: 'queued';
				};
			};
		};
	};
	parameters: {
		LineupId: number;
		GroupIdPath: number;
		ChannelId: number;
		SourceId: number;
		SourceChannelId: number;
		SourceGroupIdPath: number;
		GroupId: number;
		Search: string;
		/** @description Restrict lineup channels to a match-health state. */
		MatchHealth: 'unmatched' | 'low-confidence';
		Cursor: string;
		Limit: number;
	};
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	listWatchLineups: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: components['responses']['LineupPage'];
		};
	};
	listWatchChannels: {
		parameters: {
			query?: {
				group_id?: components['parameters']['GroupId'];
				q?: components['parameters']['Search'];
				cursor?: components['parameters']['Cursor'];
				limit?: components['parameters']['Limit'];
			};
			header?: never;
			path: {
				lineup_id: components['parameters']['LineupId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: components['responses']['GuideChannelPage'];
			default: components['responses']['Error'];
		};
	};
	getWatchGuide: {
		parameters: {
			query?: {
				group_id?: components['parameters']['GroupId'];
				q?: components['parameters']['Search'];
				from?: string;
				to?: string;
				cursor?: components['parameters']['Cursor'];
				limit?: components['parameters']['Limit'];
			};
			header?: never;
			path: {
				lineup_id: components['parameters']['LineupId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: components['responses']['GuideChannelPage'];
			default: components['responses']['Error'];
		};
	};
	getWatchChannel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				channel_id: components['parameters']['ChannelId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Channel with the current guide window. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GuideChannel'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	searchXivi: {
		parameters: {
			query?: {
				q?: components['parameters']['Search'];
				scope?: 'all' | 'channels' | 'resources';
				lineup_id?: number;
				limit?: components['parameters']['Limit'];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: components['responses']['GuideChannelPage'];
			default: components['responses']['Error'];
		};
	};
	getStudioOverview: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Studio setup health and recent jobs. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						summary: components['schemas']['StudioOverview'];
						jobs: components['schemas']['OperationJob'][];
					};
				};
			};
			default: components['responses']['Error'];
		};
	};
	getGuideCoverage: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Guide mapping coverage. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CoverageSummary'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	listStudioLineups: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: components['responses']['LineupPage'];
		};
	};
	listStudioLineupGroups: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				lineup_id: components['parameters']['LineupId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Ordered lineup groups. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StudioGroupPage'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	createStudioGroup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				lineup_id: components['parameters']['LineupId'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['StudioGroupCreateRequest'];
			};
		};
		responses: {
			/** @description Manual lineup group created and attached atomically. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StudioGroupCreateResult'];
				};
			};
			/** @description Source-linked lineup group created atomically and initial sync queued. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StudioGroupCreateResult'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	listSourceGroups: {
		parameters: {
			query?: {
				playlist_id?: number;
				q?: components['parameters']['Search'];
				cursor?: components['parameters']['Cursor'];
				limit?: components['parameters']['Limit'];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Playlist groups available as one-way lineup subscriptions. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SourceGroupPage'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	copySourceGroupToLineup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				lineup_id: components['parameters']['LineupId'];
				source_group_id: components['parameters']['SourceGroupIdPath'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A manual lineup group was created from the source group's current snapshot. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SourceGroupImportResult'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	moveWorkspaceGroup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				lineup_id: components['parameters']['LineupId'];
				group_id: components['parameters']['GroupIdPath'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['PositionRequest'];
			};
		};
		responses: {
			/** @description Group position saved for this lineup. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	deleteStudioGroup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Lineup group deleted. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	updateStudioGroup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['StudioGroupUpdateRequest'];
			};
		};
		responses: {
			/** @description Lineup group updated. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	setGroupSourceLink: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SourceGroupLinkRequest'];
			};
		};
		responses: {
			/** @description Source link saved and initial reconciliation queued. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OperationJobReference'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	disconnectGroupSourceLink: {
		parameters: {
			query?: {
				retain_channels?: boolean;
			};
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Source link disconnected. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	syncSourceGroup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Reconciliation queued. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OperationJobReference'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	listWorkspaceChannels: {
		parameters: {
			query?: {
				q?: components['parameters']['Search'];
				/** @description Restrict lineup channels to a match-health state. */
				match?: components['parameters']['MatchHealth'];
				cursor?: components['parameters']['Cursor'];
				limit?: components['parameters']['Limit'];
			};
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Ordered channels in a lineup group. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkspaceChannelPage'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	batchAddWorkspaceChannels: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkspaceBatchAddRequest'];
			};
		};
		responses: {
			/** @description Canonical lineup channels created with manually locked source variants. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						channel_ids: number[];
						total: number;
					};
				};
			};
			default: components['responses']['Error'];
		};
	};
	addSourceGroupToStudioGroup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
				source_group_id: components['parameters']['SourceGroupIdPath'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Missing channels from the source group were appended as manual channels. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SourceGroupImportResult'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	batchRemoveWorkspaceChannels: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkspaceBatchRemoveRequest'];
			};
		};
		responses: {
			/** @description Canonical lineup channels removed. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	batchMoveWorkspaceChannels: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkspaceBatchMoveRequest'];
			};
		};
		responses: {
			/** @description Selected channels moved as an ordered block. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	moveWorkspaceChannel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				group_id: components['parameters']['GroupIdPath'];
				channel_id: components['parameters']['ChannelId'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['PositionRequest'];
			};
		};
		responses: {
			/** @description Position saved. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	updateWorkspaceChannel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				channel_id: components['parameters']['ChannelId'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkspaceChannelUpdate'];
			};
		};
		responses: {
			/** @description Channel saved. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	listSourceChannels: {
		parameters: {
			query?: {
				playlist_id?: number;
				group_id?: components['parameters']['GroupId'];
				q?: components['parameters']['Search'];
				cursor?: components['parameters']['Cursor'];
				limit?: components['parameters']['Limit'];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Source catalog channels. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SourceChannelPage'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	setSourceChannelsEnabled: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					channel_ids: number[];
					enabled: boolean;
				};
			};
		};
		responses: {
			/** @description Enablement saved. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	listMatchReview: {
		parameters: {
			query?: {
				channel_id?: number;
				q?: components['parameters']['Search'];
				cursor?: components['parameters']['Cursor'];
				limit?: components['parameters']['Limit'];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Low-confidence matches requiring review. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MatchReviewPage'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	listChannelMatches: {
		parameters: {
			query?: {
				cursor?: components['parameters']['Cursor'];
				limit?: components['parameters']['Limit'];
			};
			header?: never;
			path: {
				channel_id: components['parameters']['ChannelId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Ordered source matches for a lineup channel. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MatchReviewPage'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	listChannelMatchRejections: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				channel_id: components['parameters']['ChannelId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Durable source identities rejected for this channel. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MatchRejectionPage'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	acceptChannelMatch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				channel_id: components['parameters']['ChannelId'];
				source_channel_id: components['parameters']['SourceChannelId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Match accepted and manually locked. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	rejectChannelMatch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				channel_id: components['parameters']['ChannelId'];
				source_channel_id: components['parameters']['SourceChannelId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Match rejected and its stable identity recorded. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			default: components['responses']['Error'];
		};
	};
	refreshPlaylistSource: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				source_id: components['parameters']['SourceId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			202: components['responses']['JobAccepted'];
			default: components['responses']['Error'];
		};
	};
	refreshGuideSource: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				source_id: components['parameters']['SourceId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			202: components['responses']['JobAccepted'];
			default: components['responses']['Error'];
		};
	};
	publishLineup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				lineup_id: components['parameters']['LineupId'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			202: components['responses']['JobAccepted'];
			default: components['responses']['Error'];
		};
	};
	listJobs: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Recent operation jobs. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OperationJobPage'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	getJob: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				job_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Operation job. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OperationJob'];
				};
			};
			default: components['responses']['Error'];
		};
	};
	subscribeToEvents: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Resumable Server-Sent Event snapshots for jobs and resources. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/event-stream': string;
				};
			};
		};
	};
}
