package routes

import (
	"time"
	"xivi/backend/app/controllers"
	"xivi/backend/pkg/middleware"

	"github.com/gofiber/fiber/v2"
)

// V2Routes exposes the product interface API. Public media and virtual tuner
// contracts are registered separately.
func V2Routes(a *fiber.App) {
	v2 := a.Group("/api/v2")

	// Explicitly anonymous security bootstrap and login surface.
	v2.Get("/auth/bootstrap-status", middleware.DeclareRoutePolicy("anonymous"), middleware.BoundedRateLimit(60, time.Minute, false), controllers.V2BootstrapStatus)
	v2.Post("/auth/login", middleware.DeclareRoutePolicy("anonymous"), controllers.V2Login)
	v2.Post("/auth/login/mfa", middleware.DeclareRoutePolicy("anonymous"), middleware.BoundedRateLimit(30, 15*time.Minute, false), controllers.V2CompleteMFALogin)

	auth := v2.Group("", middleware.DeclareRoutePolicy("authenticated"), middleware.RequireAuthenticated())
	auth.Get("/auth/session", controllers.V2Session)
	auth.Post("/auth/logout", middleware.CSRFProtected(), controllers.V2Logout)
	auth.Post("/auth/password", middleware.CSRFProtected(), controllers.V2ChangePassword)

	ready := auth.Group("", middleware.RequirePasswordChanged())
	ready.Post("/auth/reauth", middleware.BoundedRateLimit(20, 15*time.Minute, false), middleware.CSRFProtected(), controllers.V2Reauthenticate)
	ready.Post("/auth/mfa/enroll", middleware.CSRFProtected(), middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2MFAEnroll)
	ready.Post("/auth/mfa/confirm", middleware.CSRFProtected(), middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2MFAConfirm)
	ready.Delete("/auth/mfa", middleware.CSRFProtected(), middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2MFADisable)
	ready.Post("/auth/mfa/recovery-codes", middleware.CSRFProtected(), middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2MFARegenerateRecoveryCodes)
	ready.Get("/auth/sessions", controllers.V2AccountSessions)
	ready.Delete("/auth/sessions/:session_id", middleware.CSRFProtected(), controllers.V2RevokeAccountSession)
	ready.Get("/auth/trusted-browsers", controllers.V2AccountTrustedBrowsers)
	ready.Delete("/auth/trusted-browsers", middleware.CSRFProtected(), controllers.V2RevokeAllAccountTrustedBrowsers)
	ready.Delete("/auth/trusted-browsers/:browser_id", middleware.CSRFProtected(), controllers.V2RevokeAccountTrustedBrowser)
	ready.Patch("/account/profile", middleware.CSRFProtected(), middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2UpdateAccountProfile)

	watch := ready.Group("", middleware.DeclareRoutePolicy("viewer"))
	watch.Get("/watch/lineups", controllers.V2WatchLineups)
	watch.Get("/watch/lineups/:lineup_id/groups", middleware.RequireLineupAccess("lineup_id"), controllers.V2WatchLineupGroups)
	watch.Get("/watch/lineups/:lineup_id/channels", middleware.RequireLineupAccess("lineup_id"), controllers.V2WatchChannels)
	watch.Get("/watch/lineups/:lineup_id/channels/:channel_id/neighbors", middleware.RequireLineupAccess("lineup_id"), controllers.V2WatchChannelNeighbors)
	watch.Get("/watch/lineups/:lineup_id/guide", middleware.RequireLineupAccess("lineup_id"), controllers.V2WatchGuide)
	watch.Get("/watch/channels/:channel_id", controllers.V2WatchChannel)
	watch.Get("/search", middleware.BoundedRateLimit(120, time.Minute, false), controllers.V2Search)
	watch.Post("/stream/prewarm/:stream_id", middleware.CSRFProtected(), middleware.RequirePlayback(), controllers.V2PrewarmStream)
	watch.Post("/watch/playback/release", middleware.CSRFProtected(), controllers.V2ReleasePlayback)
	watch.Post("/stream/telemetry", middleware.CSRFProtected(), controllers.V2StreamTelemetry)

	account := ready.Group("/account", middleware.DeclareRoutePolicy("authenticated"), middleware.CSRFProtected())
	account.Get("/media-keys", controllers.V2AccountMediaKeys)
	account.Post("/media-keys", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2CreateAccountMediaKey)
	account.Delete("/media-keys/:key_id", controllers.V2RevokeAccountMediaKey)

	studio := v2.Group("/studio", middleware.DeclareRoutePolicy("admin"), middleware.RequireAdmin(), middleware.RequirePasswordChanged(), middleware.BoundedRateLimit(240, time.Minute, true), middleware.CSRFProtected())
	studio.Get("/users", controllers.V2StudioUsers)
	studio.Get("/security/audit", controllers.V2StudioSecurityAudit)
	studio.Post("/users", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2CreateStudioUser)
	studio.Patch("/users/:user_id", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2UpdateStudioUser)
	studio.Patch("/users/:user_id/profile", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2UpdateStudioUserProfile)
	studio.Post("/users/:user_id/password-reset", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2ResetStudioUserPassword)
	studio.Delete("/users/:user_id/mfa", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2ResetStudioUserMFA)
	studio.Delete("/users/:user_id", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2DeleteStudioUser)
	studio.Delete("/users/:user_id/sessions", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2RevokeStudioUserSessions)
	studio.Delete("/users/:user_id/media-keys", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2RevokeStudioUserMediaKeys)
	studio.Get("/users/:user_id/media-keys", controllers.V2StudioUserMediaKeys)
	studio.Delete("/users/:user_id/media-keys/:key_id", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2RevokeStudioUserMediaKey)
	studio.Get("/overview", controllers.V2StudioOverview)
	studio.Get("/streaming/status", controllers.V2StreamingStatus)
	studio.Get("/streams", controllers.V2StudioStreams)
	studio.Get("/streams/history/:incident_id", controllers.V2StudioStreamHistory)
	studio.Post("/streams/:stream_id/failover", controllers.V2FailoverStream)
	studio.Post("/streams/:stream_id/restart", controllers.V2RestartStream)
	studio.Delete("/streams/:stream_id", controllers.V2StopStream)
	studio.Delete("/streams/:stream_id/connections/:connection_id", controllers.V2DisconnectStreamClient)
	studio.Get("/device-outputs", controllers.V2DeviceOutputs)
	studio.Patch("/device-outputs/virtual-tuner/:lineup_id", controllers.V2SetLineupVirtualTunerEnabled)
	studio.Post("/device-outputs/virtual-tuner/:lineup_id/credential/rotate", middleware.RequireRecentReauthentication(5*time.Minute), controllers.V2RotateLineupVirtualTunerCredential)
	studio.Patch("/device-outputs/fill-missing-guide-slots/:lineup_id", controllers.V2SetLineupFillMissingGuideSlots)
	studio.Get("/guide-data/coverage", controllers.V2StudioCoverage)
	studio.Get("/lineups", controllers.V2StudioLineups)
	studio.Get("/lineups/:lineup_id/groups", controllers.V2StudioLineupGroups)
	studio.Get("/lineups/:lineup_id/duplicate-tvg-ids", controllers.V2StudioDuplicateTVGIDs)
	studio.Put("/lineups/:lineup_id/duplicate-tvg-ids/review", controllers.V2SetStudioDuplicateTVGIDReview)
	studio.Post("/lineups/:lineup_id/duplicate-tvg-ids/merge", controllers.V2MergeStudioDuplicateTVGID)
	studio.Post("/lineups/:lineup_id/groups", controllers.V2CreateStudioGroup)
	studio.Patch("/lineups/:lineup_id/groups/:group_id/position", controllers.V2MoveStudioGroup)
	studio.Post("/lineups/:lineup_id/source-groups/:source_group_id/copy", controllers.V2CopySourceGroupToLineup)
	studio.Get("/source-groups", controllers.V2StudioSourceGroups)
	studio.Patch("/source-groups/:source_group_id/enabled", controllers.V2SetStudioSourceGroupEnabled)
	studio.Patch("/groups/:group_id", controllers.V2UpdateStudioGroup)
	studio.Delete("/groups/:group_id", controllers.V2DeleteStudioGroup)
	studio.Put("/groups/:group_id/source-link", controllers.V2SetStudioGroupSourceLink)
	studio.Delete("/groups/:group_id/source-link", controllers.V2DeleteStudioGroupSourceLink)
	studio.Post("/groups/:group_id/sync", controllers.V2SyncStudioGroup)
	studio.Get("/groups/:group_id/channels", controllers.V2StudioGroupChannels)
	studio.Post("/groups/:group_id/channels/batch-add", controllers.V2BatchAddStudioChannels)
	studio.Post("/groups/:group_id/source-groups/:source_group_id/add", controllers.V2AddSourceGroupToStudioGroup)
	studio.Post("/groups/:group_id/channels/batch-remove", controllers.V2BatchRemoveStudioChannels)
	studio.Post("/groups/:group_id/channels/batch-move", controllers.V2BatchMoveStudioChannels)
	studio.Patch("/groups/:group_id/channels/:channel_id/position", controllers.V2MoveStudioChannel)
	studio.Patch("/channels/:channel_id", controllers.V2UpdateStudioChannel)
	studio.Get("/source-channels", controllers.V2StudioSourceChannels)
	studio.Get("/source-channels/:source_channel_id/logo", middleware.BoundedRateLimit(120, time.Minute, false), controllers.V2StudioSourceChannelLogo)
	studio.Patch("/source-channels/enabled", controllers.V2SetStudioSourceChannelsEnabled)
	studio.Get("/review", controllers.V2StudioReview)
	studio.Get("/channels/:channel_id/matches", controllers.V2StudioReview)
	studio.Get("/channels/:channel_id/suggestions", controllers.V2StudioMatchSuggestions)
	studio.Get("/channels/:channel_id/rejections", controllers.V2StudioMatchRejections)
	studio.Delete("/channels/:channel_id/rejections/:rejection_id", controllers.V2DeleteStudioMatchRejection)
	studio.Post("/channels/:channel_id/matches/:source_channel_id/accept", controllers.V2AcceptStudioMatch)
	studio.Patch("/channels/:channel_id/matches/:source_channel_id/position", controllers.V2MoveStudioMatch)
	studio.Post("/channels/:channel_id/matches/:source_channel_id/reject", controllers.V2RejectStudioMatch)
	studio.Post("/sources/:source_id/refresh", controllers.V2RefreshSource)
	studio.Post("/guide-data/sources/:source_id/refresh", controllers.V2RefreshGuideSource)
	studio.Post("/lineups/:lineup_id/publish", controllers.V2PublishLineup)

	admin := v2.Group("", middleware.DeclareRoutePolicy("admin"), middleware.RequireAdmin(), middleware.RequirePasswordChanged())
	admin.Get("/jobs", controllers.V2Jobs)
	admin.Get("/jobs/:job_id", controllers.V2Job)
	admin.Get("/events", controllers.V2Events)
}
